name: Interactive Label CI

on: [push]

jobs:
  build-and-test-python:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build Python lint and test
      run: |
        cp config.tmpl.env config.env
        cd development && docker-compose up --build -d
    - name: Run Python lint and test
      run: docker exec labelinteractive make linttest

  build-and-test-js:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build Javascript lint and test
      run: |
        cd testing && docker-compose up --build -d
        docker exec javascripttests make install
    - name: Run Javascript lint and test
      run: docker exec javascripttests make linttestjs
